# Generated by Django 6.0.5 on 2026-05-18 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('cashapp', 'CashApp'), ('paypal', 'PayPal'), ('bank', 'Bank Transfer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('memo_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cashapp_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('maximum_deposit', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proof_image', models.ImageField(upload_to='proofs/%Y/%m/%d/')),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_info', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposits.paymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
