# Generated by Django 6.0.5 on 2026-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Withdrawal', 'verbose_name_plural': 'Withdrawals'},
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='recipient_address',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='cashapp_tag',
            field=models.CharField(blank=True, help_text='Your $Cashtag', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN for international transfers', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='memo_tag',
            field=models.CharField(blank=True, help_text='Memo/Destination tag (if required)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='network',
            field=models.CharField(blank=True, help_text='Network (ERC20, TRC20, BEP20, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='Your PayPal email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='routing_number',
            field=models.CharField(blank=True, help_text='Routing/ABA number (US banks)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code for international transfers', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Your crypto wallet address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_method',
            field=models.CharField(choices=[('crypto', 'Cryptocurrency'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('cashapp', 'CashApp')], default='crypto', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='crypto_currency',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT', 'USDT (TRC20)'), ('USDC', 'USDC (ERC20)'), ('SOL', 'Solana (SOL)'), ('BNB', 'Binance Coin (BNB)'), ('XRP', 'Ripple (XRP)'), ('DOGE', 'Dogecoin (DOGE)'), ('ADA', 'Cardano (ADA)'), ('LTC', 'Litecoin (LTC)')], max_length=10, null=True),
        ),
    ]
